redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5

nestjs-bullmq:
  image:
    repository: ga89qin/nestjs-bullmq
    tag: v1
  service:
    type: LoadBalancer
    port: 80
  env:
    REDIS_HOST: nestjs-bullmq-redis-master
    REDIS_PORT: 6379