apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-bullmq
    app.kubernetes.io/managed-by: Helm
  name: nestjs-bullmq
  annotations:
    meta.helm.sh/release-name: nestjs-bullmq
    meta.helm.sh/release-namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-bullmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nestjs-bullmq
    spec:
      containers:
        - image: ga89qin/nestjs-bullmq:v1
          env:
            - name: REDIS_HOST
              value: redis-master.redis.svc.cluster.local
            - name: REDIS_PORT
              value: '6379'
          name: nestjs-bullmq
          ports:
            - containerPort: 3000
          resources: {}
status: {}